// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// indmodelseC
List indmodelseC(SEXP land_r, int nrow, int ncol, int n_steps, int init_population, int hr_size, double birth_rate, int breeding_age, double survival, double distance_weight, double dispersal_distance, int dispersal_mode, double sink_avoidance, double neigh_avoidance, double sink_mortality, const char* file_name);
RcppExport SEXP PopIn_indmodelseC(SEXP land_rSEXP, SEXP nrowSEXP, SEXP ncolSEXP, SEXP n_stepsSEXP, SEXP init_populationSEXP, SEXP hr_sizeSEXP, SEXP birth_rateSEXP, SEXP breeding_ageSEXP, SEXP survivalSEXP, SEXP distance_weightSEXP, SEXP dispersal_distanceSEXP, SEXP dispersal_modeSEXP, SEXP sink_avoidanceSEXP, SEXP neigh_avoidanceSEXP, SEXP sink_mortalitySEXP, SEXP file_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type land_r(land_rSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< int >::type n_steps(n_stepsSEXP);
    Rcpp::traits::input_parameter< int >::type init_population(init_populationSEXP);
    Rcpp::traits::input_parameter< int >::type hr_size(hr_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type birth_rate(birth_rateSEXP);
    Rcpp::traits::input_parameter< int >::type breeding_age(breeding_ageSEXP);
    Rcpp::traits::input_parameter< double >::type survival(survivalSEXP);
    Rcpp::traits::input_parameter< double >::type distance_weight(distance_weightSEXP);
    Rcpp::traits::input_parameter< double >::type dispersal_distance(dispersal_distanceSEXP);
    Rcpp::traits::input_parameter< int >::type dispersal_mode(dispersal_modeSEXP);
    Rcpp::traits::input_parameter< double >::type sink_avoidance(sink_avoidanceSEXP);
    Rcpp::traits::input_parameter< double >::type neigh_avoidance(neigh_avoidanceSEXP);
    Rcpp::traits::input_parameter< double >::type sink_mortality(sink_mortalitySEXP);
    Rcpp::traits::input_parameter< const char* >::type file_name(file_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(indmodelseC(land_r, nrow, ncol, n_steps, init_population, hr_size, birth_rate, breeding_age, survival, distance_weight, dispersal_distance, dispersal_mode, sink_avoidance, neigh_avoidance, sink_mortality, file_name));
    return rcpp_result_gen;
END_RCPP
}
